# Generated by Django 3.1.6 on 2022-07-04 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=200)),
                ('mname', models.CharField(max_length=200)),
                ('sname', models.CharField(max_length=200)),
                ('bday', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=None)),
                ('sex', models.CharField(max_length=200)),
                ('add', models.CharField(max_length=200)),
                ('eml', models.CharField(max_length=200)),
                ('mbl', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dttoday', models.DateField(auto_now_add=True)),
                ('sncwhen', models.TextField(default=None)),
                ('md', models.TextField(default=None)),
                ('cs', models.TextField(default=None)),
                ('dcd', models.TextField(default=None)),
                ('patientid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tolsys.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kdsession', models.TextField(default=None)),
                ('tpsession', models.TextField(default=None)),
                ('adate', models.TextField(default=None)),
                ('atime', models.TextField(default=None)),
                ('patientid', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='tolsys.patient')),
            ],
        ),
    ]
