# Generated by Django 3.1.6 on 2022-07-05 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tolsys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='dttoday',
            field=models.DateField(default=None),
        ),
    ]
